// ==== (core: game shell, network, share codes, editor actions)
// ============================================================
//  English.
//
//  Keys are the Japanese source strings, exactly as they appear in `src`.
//  See i18n.js for why. A key with no entry here renders in Japanese, so a
//  half-finished catalogue is a mixed interface rather than a broken one —
//  `node tools/check-i18n.mjs` lists whatever is still missing.
//
//  Two rules held throughout:
//
//  1. THE DESIGN DOCUMENT'S VOCABULARY DOES NOT APPEAR HERE either. The
//     Japanese says 「機体を組む」, not the internal name for that screen,
//     and the English says "Build" for the same reason.
//
//  2. Length matters more than in most interfaces. Japanese carries a word
//     in three or four characters where English needs ten, and every one of
//     these sits in a panel sized for the Japanese. Where the literal
//     translation would not fit, the shorter true thing wins over the
//     longer exact one — "Mirror" rather than "Copy mirrored to the other
//     side" — and the long form goes in the tooltip.
// ============================================================

export const CORE = {

  // ---- src/core/Presets.js
  '腕 ARM': 'ARM',
  '脚 LEG': 'LEG',
  '頭 HEAD': 'HEAD',
  '上半身 UPPER BODY': 'UPPER BODY',

  // ---- src/core/Share.js
  'BLOSTOM の共有コードではありません': 'Not a BLOSTOM share code',
  '共有コードが壊れています': 'This share code is damaged',
  'この環境では圧縮コードを読めません': 'Compressed codes cannot be read here',
  'BLOSTOM のデータではありません': 'Not BLOSTOM data',

  // ---- src/editor/EditorScene.js
  '戻れる選択がありません': 'No earlier selection to go back to',
  '色を持つブロックを選んでください': 'Select a block that has a colour',
  '反対側のパーツが見つかりません': 'No matching part on the other side',
  '最後に置いたパーツがありません': 'Nothing has been placed yet',
  '保存する選択がありません': 'Nothing selected to save',
  'そのまとまりのパーツはもうありません': 'That group no longer exists',
  '埋まっているブロックはありません': 'No buried blocks',
  '{0} 個が他のブロックの中に完全に埋まっています': '{0} are completely inside other blocks',
  '面につけたパーツを選んでください': 'Select a part attached to a face',
  '別の面へ': 'Next face',
  '削除 ({0})': 'Delete ({0})',
  削除: 'Delete',
  'コピーしたパーツがありません': 'Nothing has been copied',
  '貼り付ける面にカーソルを合わせてください': 'Point at the face to paste onto',
  'カーソルの面に貼り付け': 'Paste onto face',
  連結: 'Attach',
  連結解除: 'Detach',
  回転: 'Rotate',
  移動: 'Move',
  '回転 {0}°': 'Rotate {0}°',
  '移動 {0}, {1}, {2} ・ 計 {3}m': 'Move {0}, {1}, {2} ・ {3}m total',
  '寸法 x{0}': 'Size x{0}',
  '面につけたブロックを選んでください': 'Select a block attached to a face',
  '面に合わせる': 'Align to face',
  '合わせられる面がありません': 'No face to align to',
  '基準にするボーンを最後に選んでください': 'Select the reference bone last',
  '揃えるボーンを選んでください': 'Select the bones to align',
  'ボーンを揃える': 'Align bones',
  寸法変更: 'Resize',
  装備変更: 'Change equipment',
  '{0}は1枚しか付けられません': 'Only one {0} can be fitted',
  '装備の大きさ': 'Equipment size',
  回転設定: 'Spin settings',
  'その色は使われていません': 'That colour is not in use',
  色の置き換え: 'Replace colour',
  弾の色: 'Shot colour',
  ボーン追加: 'Add bone',
  ボーン寸法: 'Bone size',
  '{0}個のブロックの加工が消えます。形を変えますか？': 'Sculpting on {0} blocks will be lost. Change the shape?',
  形状: 'Shape',
  サークル半径: 'Ring radius',
  サークルの向き: 'Ring facing',
  'ボーンの動き': 'Bone motion',
  '武器の構え': 'Weapon stance',
  'もとにするボーンを最後に選んでください': 'Select the source bone last',
  '反対側のボーンが見つかりません': 'No matching bone on the other side',
  '反対側へコピー': 'Copy to other side',
  '先まとめて効き': 'Gain, whole chain',
  '関節の効き': 'Joint gain',
  位置変更: 'Move',
  'つなぎ替えるパーツを選んでください': 'Select the parts to re-attach',
  '新しい連結先をクリック（Escで中止）': 'Click the new parent (Esc to cancel)',
  'つなぎ替えを中止しました': 'Re-attach cancelled',
  'そこにはつなげられません': 'Cannot attach there',
  連結先変更: 'Re-attach',
  '反転するパーツを選んでください': 'Select the parts to mirror',
  'その場で反転': 'Mirror in place',
  '中心線の上にあるパーツは、反転しても同じ場所です': 'A part on the centre line mirrors onto itself',
  左右反転コピー: 'Mirror copy',
  '2つ以上えらんでください': 'Select two or more',
  で揃える: 'align',
  に均等: 'space evenly',
  の手前で揃える: 'align near side',
  の奥で揃える: 'align far side',
  '同じパーツにつながっているもの同士でしか揃えられません': 'Only parts on the same parent can be aligned together',
  '{0}個ならべる': 'Line up {0}',
  '端の2つと、間に置くものを選んでください': 'Select the two ends and what goes between',
  '端の2つは同じパーツにつながっている必要があります': 'The two ends must share a parent',
  あいだに置く: 'Place between',
  '間に置くものが端と同じパーツにつながっていません': 'What goes between is on a different parent',
  '肢を作る': 'Make a limb',
  '左右で食い違っているパーツはありません': 'Nothing differs between left and right',
  '円周に{0}個': '{0} around a circle',
  '複製（数値）': 'Duplicate (numeric)',
  '基準にするパーツを最後に選んでください': 'Select the reference part last',
  '揃えるパーツを選んでください': 'Select the parts to align',
  '傾きを揃える': 'Match rotation',
  '基準にするブロックを最後に選んでください': 'Select the reference block last',
  '揃えるブロックを選んでください': 'Select the blocks to match',
  '見た目を揃える': 'Match appearance',
  中心へ: 'To centre',
  '傾きを戻す': 'Clear rotation',
  '繰り返せる操作がありません': 'Nothing to repeat',
  '名前を付ける': 'Name it',
  複製: 'Duplicate',
  面: 'Face',
  中心: 'Centre',
  'ボーン {0}': 'Bone {0}',
  'パーツ {0}': 'Part {0}',
  ' 高さ {0}': ' height {0}',
  ' ・端': ' ・edge',
  ' ・隣の{0}に合わせた': ' ・matched to the {0} beside it',
  'ブロックはこれ以上大きくできません（上限 {0}）': 'This block cannot grow further (limit {0})',
  '盛る（ブロック拡張）': 'Add (grow the block)',
  '{0} {1}cm': '{0} {1}cm',
  塗りつぶし: 'Fill',
  ならす: 'Smooth',
  平らに: 'Flatten',
  '穴をあける': 'Drill',
  '加工を取り消す': 'Reset sculpt',
  'ブロックが消えないよう、中心を1マス残しました': 'One cell was kept at the centre so the block survives',
  '{0}は{1}個までです。どれかを外してください': 'Up to {1} {0}. Remove one first',
  '武器は{0}枚までです。どれかを外してください': 'Up to {0} weapons. Remove one first',
  '{0}は{1}個までです': 'Up to {1} {0}',
  '{0}は{1}と一緒には付けられません': '{0} cannot be fitted alongside {1}',
  パーツ配置: 'Place part',
  '配置 {0}': 'Place {0}',
  ボーン配置: 'Place bone',
  '配置 {0}{1}': 'Place {0}{1}',

  // ---- src/main.js
  'これ以上戻せません': 'Nothing further to undo',
  '元に戻す: {0}': 'Undo: {0}',
  'やり直せる操作がありません': 'Nothing to redo',
  'やり直し: {0}': 'Redo: {0}',
  '{0} に移動しました': 'Moved to {0}',
  'ソロランでは撃たせないようにはできません': 'Enemy fire cannot be turned off during a solo run',
  '敵が撃ってきます': 'Enemies will shoot',
  '敵は撃ってきません': 'Enemies will hold fire',
  'コピーするパーツを選んでください': 'Select the parts to copy',
  '{0} パーツを切り取りました': 'Cut {0} parts',
  '{0} パーツをコピーしました': 'Copied {0} parts',
  'クリップボードが空です': 'The clipboard is empty',
  '{0} パーツをカーソルの面に貼り付けました': 'Pasted {0} parts onto the face',
  '貼り付け': 'Paste',
  '貼り付けできませんでした': 'Could not paste',
  '{0} パーツを貼り付けました': 'Pasted {0} parts',
  '「{0}」を保存しました': 'Saved “{0}”',
  '復元できる作業がありません': 'There is nothing to restore',
  '前回の続きから復元しました': 'Restored where you left off',
  '保存できませんでした（容量不足）': 'Could not save — out of space',
  見つかりません: 'Not found',
  '「{0}」を開きます': 'Opening “{0}”',
  '「{0}」を開く': 'Open “{0}”',
  '「{0}」を開きました': 'Opened “{0}”',
  '保存していない変更があります。{0}破棄しますか？': 'There are unsaved changes. {0}Discard them?',
  '保存データがありません': 'No saved data',
  読み込みました: 'Loaded',
  '{0} を読み込みました': 'Loaded {0}',
  '読み込みに失敗しました': 'Could not load it',
  '{0} を読み込みます': 'Loading {0}',
  '{0} を読み込む': 'Load {0}',
  'パーツが見つかりません': 'Part not found',
  '新しいパーツを作成しました': 'Started a new part',
  'パーツ庫に「{0}」を保存しました': 'Saved “{0}” to the parts store',
  '保存するパーツを選んでください': 'Select the parts to save',
  'パーツ庫に「{0}」を保存しました（{1} パーツ）': 'Saved “{0}” to the parts store ({1} parts)',
  '「{0}」を置く場所をクリック': 'Click where “{0}” goes',
  '「{0}」を削除しました': 'Deleted “{0}”',
  'パーツ庫「{0}」': 'Parts store “{0}”',
  共有コード読み込み: 'Load share code',
  メイン編集: 'Main build',
  '2つ以上選んでください。最後に選んだパーツが連結先になります': 'Select two or more. The last one selected becomes the parent',
  '連結できませんでした（自分の子には連結できません）': 'Could not attach — a part cannot hang from its own child',
  '{0} 個は対象外': '{0} not eligible',
  '{0} 個はボーンの固定側': '{0} on the fixed side of a bone',
  '{0} パーツを {1} に連結しました{2}': 'Attached {0} parts to {1}{2}',
  '{0} パーツの連結を解除しました': 'Detached {0} parts',
  '解除できる連結がありません': 'Nothing to detach',
  'カラーが上限に達しました': 'No colour slots left',
  'この機体には細かすぎます。ブロックを減らすと 1/{0} にできます': 'Too fine for this machine. Fewer blocks would allow 1/{0}',
  '加工したブロックが{0}個あります。粗くすると細部が失われます。': '{0} blocks are sculpted. Going coarser loses the detail.',
  加工の細かさ: 'Sculpt detail',
  '加工の細かさを 1/{0} にしました': 'Sculpt detail set to 1/{0}',
  全埋め: 'Fill solid',
  角落とし: 'Chamfer',
  塗る: 'Paint',

  // ---- src/net/Matchmaker.js
  'この環境ではマッチングできません': 'Matchmaking is not available here',
  'マッチングサーバーにつながりません（{0}）': 'Cannot reach the matchmaking server ({0})',
  '対戦相手を探しています': 'Looking for an opponent',
  '相手が離脱しました': 'Your opponent left',
  '{0} — 接続しています': '{0} — connecting',
  接続しました: 'Connected',
  '接続できませんでした（相手のネットワークが厳しいようです）': 'Could not connect — their network appears to be restrictive',

  // ---- src/net/Session.js
  '同期がずれました（{0}歩目）': 'The fights have drifted apart (step {0})',
  '{0}が抜けました（CPUが引き継ぎます）': '{0} left — the computer takes over',
  '相手が抜けました': 'Your opponent left',

  // ---- src/net/Transport.js
  'Steamがありません': 'Steam is not running',

  // ---- src/ui/dom.js
  '{0} {1} — Altを押しながら左右にドラッグ、「0.5*3」のような式も打てます':
    '{0} {1} — hold Alt and drag sideways; sums like “0.5*3” work too',
  'ドラッグでサイズ変更 / ダブルクリックで戻す': 'Drag to resize / double-click to reset',

};
