// ============================================================
//  The workbench, in English.
//
//  Everything here sits in a panel whose width was chosen for Japanese,
//  which says in four characters what English needs a dozen for. Where the
//  literal translation would wrap or clip, the short true one wins and the
//  long one moves to the tooltip beside it — 「反対側」 is "Other side",
//  not "Jump to the matching part on the other side", because that
//  sentence is already the tooltip underneath.
// ============================================================

export const EDITOR = {

  // ---- the read-out at the bottom
  重心を出せません: 'Cannot work out the balance point',
  中央: 'Centre',
  '右に {0}m': '{0}m right',
  '左に {0}m': '{0}m left',
  ' / 前に {0}m': ' / {0}m forward',
  ' / 後ろに {0}m': ' / {0}m back',
  '重心: 高さ {0}m ・ {1}{2}': 'Balance: {0}m up ・ {1}{2}',
  '{0}個を隠しています': '{0} hidden',
  '{0}個を固定しています': '{0} locked',
  '幅 {0}': 'Width {0}',

  // ---- the first time anybody opens the workbench
  'ようこそ': 'Welcome',
  '① 上の「プリセット」から機体を選ぶ。まずはそれで十分です':
    '① Pick a machine from “Presets” above. That is enough to start with',
  '② 左のツールでブロックを足し、ボーンで関節を作る':
    '② Add blocks with the tools on the left, and bones to make joints',
  '③ 「装備プレート」で武器とブーストを貼る':
    '③ Stick weapons and boosters on with “Plates”',
  '④ 右上の「テスト」で動かしてみる': '④ Try it with “Test”, top right',
  'はじめる': 'Start',
  'もっと詳しく': 'Tell me more',

  // ---- history and drafts
  'まだ何もしていません。': 'Nothing done yet.',
  直前: 'Last',
  '{0}手前': '{0} back',
  '編集の履歴': 'History',
  '前回の作業が残っています': 'Your last session is still here',
  復元する: 'Restore',
  あとで: 'Later',
  破棄: 'Discard',
  '保存していない変更があります': 'There are unsaved changes',

  // ---- files
  'まだありません。「名前を付けて保存」で残せます。': 'Nothing yet — “Save as” keeps one.',
  'この保存を削除': 'Delete this save',
  'プリセット…': 'Presets…',
  まっさら: 'Empty',
  コアのみ: 'Core only',
  'タイトル画面に戻ります': 'Back to the title screen',
  '⌂ タイトル': '⌂ Title',
  'パーツ編集': 'Edit part',
  '元に戻す (Ctrl+Z)': 'Undo (Ctrl+Z)',
  'やり直し (Ctrl+Y)': 'Redo (Ctrl+Y)',
  '保存（上書き）': 'Save',
  '名前を付けて保存': 'Save as',
  '名前を付けて保存…': 'Save as…',
  '上書き保存から読込': 'Load the saved copy',
  '前回の作業を復元': 'Restore last session',
  '保存したもの': 'Saved',
  'ファイルに書き出す': 'Export to a file',
  'ファイルから読み込む': 'Import from a file',
  'QRで共有 / 読み込み': 'Share or load by QR',
  'ファイル ▾': 'File ▾',
  '使い方 (F1)': 'Help (F1)',
  'キー設定': 'Controls',
  'パーツ庫に保存': 'Save to the parts store',
  '⧉ 共有': '⧉ Share',
  新規: 'New',
  '「パーツ庫」から呼び出せます': 'Available from the parts store',
  '← メイン編集': '← Main build',

  // ---- the gizmo and its frames
  '移動 (T)': 'Move (T)',
  '回転 (R)': 'Rotate (R)',
  切らない: 'Off',
  '左右で切る': 'Left / right',
  '上下で切る': 'Up / down',
  '前後で切る': 'Front / back',
  '上下・前後・左右のまま動かします': 'Moves along the world axes',
  '地面の向き': 'World',
  'そのパーツが向いている方向に沿って動かします': 'Moves along the part’s own facing',
  'パーツの向き': 'Part',
  動かす: 'Move',
  'グリッドと角度にスナップ': 'Snap to grid and angle',
  グリッド: 'Grid',
  角度: 'Angle',
  面からの隙間: 'Gap from face',
  'えらんだパーツを機体の中心線に戻します': 'Puts the selection back on the centre line',
  '親から受け継いだ傾きを打ち消して、まっすぐにします': 'Cancels the tilt inherited from the parent',
  'コピーせず、その場で向きを反転します（⇧F）': 'Flips in place without copying (⇧F)',
  '最初に選んだ2つの中間に、残りを置きます': 'Puts the rest between the first two selected',
  面いっぱい: 'Fill face',
  'ついている面いっぱいの大きさにします': 'Grows to fill the face it is on',

  // ---- selecting
  選ぶ: 'Select',
  全選択: 'All',
  配下ごと: 'With children',
  '選んだパーツの下にあるもの全部を足します（削除で消えるのと同じ範囲）':
    'Adds everything hanging below — the same reach as deleting',
  '同じ種類': 'Same kind',
  '同じ形のブロック・同じ種類のプレートを全部足します':
    'Adds every block of that shape and every plate of that kind',
  '同じ色': 'Same colour',
  '同じ色のブロックを全部選びます': 'Selects every block of that colour',
  反対側: 'Other side',
  '反対側の相棒に飛びます': 'Jumps to the matching part on the other side',
  '選択を戻す': 'Back',
  'ひとつ前の選択に戻ります': 'Returns to the previous selection',
  '最後に置いたもの': 'Last placed',
  '最後に置いたパーツに戻ります': 'Returns to the part placed last',
  'えらんだパーツに名前を付けます': 'Names the selected parts',
  'まとまりとして残す': 'Keep as a group',
  '今の選択を残す': 'Keep this selection',
  '選び出すのに手間のかかる組を、名前を付けて残します':
    'Names a selection that is fiddly to make again',

  // ---- multiplying
  ふやす: 'Add',
  コピー: 'Copy',
  切取: 'Cut',
  貼付: 'Paste',
  'Shift+V でカーソルの面に貼れます': 'Shift+V pastes onto the face under the cursor',
  '選択したパーツを、機体の中心線の反対側にコピーします':
    'Copies the selection to the other side of the centre line',
  'もう一度': 'Again',
  '直前の操作をもう一度（Ctrl+R）': 'Repeat the last action (Ctrl+R)',
  '同じ武器は{0}枚までです': 'Up to {0} of the same weapon',
  '肢をつくる': 'Make a limb',
  脚: 'Leg',
  腕: 'Arm',
  '脚（3節）': 'Leg (3 joints)',
  '円周にならべる': 'Around a circle',
  個: '',

  // ---- attaching
  つなぐ: 'Attach',
  '連結 (J)': 'Attach (J)',
  '解除 (⇧J)': 'Detach (⇧J)',
  'つなぎ替え': 'Re-attach',
  'クリックしたパーツを新しい連結先にします': 'The part you click becomes the new parent',

  // ---- aligning
  そろえる: 'Align',
  揃える: 'Align',
  '平均の位置へ。いちばん動かす距離が短くなります': 'To the average — the shortest total move',
  手前で: 'Near',
  'いちばん手前のものに合わせます': 'Matches the nearest one',
  奥で: 'Far',
  'いちばん奥のものに合わせます': 'Matches the furthest one',
  均等: 'Even',
  'この向きに、自分の幅ぶんずつ繰り返します': 'Repeats along this axis, one width at a time',
  '基準に合わせる': 'Match a reference',
  '基準は最後に選んだパーツ（水色の枠）。': 'The reference is the part selected last — the blue outline.',
  傾き: 'Tilt',
  '最後に選んだパーツの傾きを、他の全部に写します': 'Copies the last part’s tilt onto the rest',
  見た目: 'Look',
  '最後に選んだブロックの形と色を、他の全部に写します': 'Copies the last block’s shape and colour onto the rest',
  '骨の太さ': 'Bone size',
  'ボーンの長さと太さを、最後に選んだものに揃えます': 'Matches bone length and thickness to the last one',

  // ---- looking
  '見る・確かめる': 'Look at it',
  正面: 'Front',
  側面: 'Side',
  上: 'Top',
  斜め: 'Angle',
  '中を見る': 'See inside',
  断面: 'Cut',
  '機体を透かす': 'Ghost',
  '隠す・固定': 'Hide and lock',
  隠す: 'Hide',
  選択だけ: 'Selected only',
  全部出す: 'Show all',
  固定する: 'Lock',
  '選んだパーツを、クリックでもギズモでも掴めなくします': 'Makes the selection unclickable and undraggable',
  '固定を解除': 'Unlock',
  調べる: 'Check',
  '左右の食い違い': 'Left / right mismatch',
  '左右で相方のいないパーツをえらびます': 'Selects parts with no partner on the other side',
  '埋まったブロック': 'Buried blocks',
  '他のブロックの中に完全に埋まっているものを探します': 'Finds blocks completely inside other blocks',
  重心: 'Balance',
  '重心の位置を出します': 'Works out where the weight sits',

  // ---- placing
  形: 'Shape',
  ' 向き　': ' facing　',
  'Shift+ホイール': 'Shift+wheel',
  ' 高さ　': ' height　',
  ドラッグ: 'Drag',
  ' 連続配置': ' place a row',
  'Alt+クリック': 'Alt+click',
  ' 写す　': ' copy　',
  右クリック: 'Right click',
  ' 削除': ' delete',
  '空中の高さ': 'Height above ground',
  'よく使う組み合わせ': 'Common set-ups',
  寸法: 'Size',
  '縦横高さを揃える': 'Lock proportions',
  'プレート径': 'Plate size',
  長さ: 'Length',
  太さ: 'Thickness',
  可動域: 'Range',
  'いまの形・寸法・色を覚えます': 'Remembers the current shape, size and colour',

  // ---- sculpting
  ブラシ: 'Brush',
  左右: 'L / R',
  上下: 'U / D',
  前後: 'F / B',
  '丸いブラシ': 'Round brush',
  '対称に加工する': 'Sculpt symmetrically',
  '対称の向き': 'Mirror axis',
  'カーソルの周りの段差をなだらかにします（K）': 'Smooths the steps around the cursor (K)',
  '見ている面から手前を平らに削ります（⇧J）': 'Shaves flat from the face you are facing (⇧J)',
  'ブロックを貫通する穴をあけます（O）': 'Drills right through the block (O)',
  'つながっている同じ色をまとめて塗ります': 'Repaints a connected patch of one colour',
  'カーソルの下の色を取ります（I）': 'Picks up the colour under the cursor (I)',
  スポイト: 'Pick',
  'このブロックの加工をすべて取り消し、元の形に戻します': 'Undoes all sculpting here and restores the shape',
  '形に戻す': 'Reset shape',
  '細かいほど重くなります。': 'Finer costs more to run.',

  // ---- panels
  '新規ブロック寸法': 'New block size',
  '装備プレート': 'Plates',
  '新規ボーン寸法': 'New bone size',
  加工設定: 'Sculpt settings',
  '「パーツ庫」の ＜配置＞ で選びます。': 'Chosen with ＜Place＞ in the parts store.',
  '選択ツール': 'Select tool',
  'クリックで選択、ドラッグで移動。': 'Click to select, drag to move.',
  '加工 (上級)': 'Sculpt (advanced)',
  組み立て: 'Assemble',
  'ツール設定': 'Tool settings',
  '左右対称でつける': 'Place on both sides',
  '歩行プレビュー': 'Walk preview',
  'サークルの円線を表示': 'Show ring lines',
  編集: 'Edit',
  'カラーサークル ▾': 'Colour wheel ▾',
  'カラーサークル ▴': 'Colour wheel ▴',
  'パーツ庫': 'Parts store',
  'パーツ一覧': 'All parts',
  '見えない所のパーツもここから': 'Reaches the parts you cannot see, too',
  色: 'Colour',
  '最近使った色': 'Recent',
  'カスタム色': 'Custom',
  'インスペクタ': 'Inspector',
  スペック: 'Stats',
  '名前・形で探す': 'Search by name or shape',
  'パーツを探す': 'Find a part',
  すべて: 'All',
  'ブロックだけ': 'Blocks only',
  'ボーンだけ': 'Bones only',
  '装備プレートだけ': 'Plates only',
  '選択中と同じ色だけ': 'Same colour as selected',
  '選択中のものだけ': 'Selected only',

  // ---- the legend across the bottom of the field
  左ドラッグ: 'Left drag',
  右ドラッグ: 'Right drag',
  平行移動: 'Pan',
  クリック: 'Click',
  '設置 / 選択': 'Place / select',
  複数選択: 'Multi-select',
  '同じ所を再クリック': 'Click the same spot again',
  '奥のパーツ': 'The part behind',
  '選択に寄る / 全体': 'Frame selection / all',
  ギズモ: 'Gizmo',
  '元に戻す': 'Undo',
  'パネルを開く / たたむ': 'Open / fold the panel',
  使い方: 'Help',
  '⟲ リスポーン': '⟲ Respawn',
  '敵に撃たせない': 'Hold enemy fire',
  'ESC で再開': 'Esc to resume',
  '▶ 再開する': '▶ Resume',
  場所: 'Arena',
  '⌨ キー設定': '⌨ Controls',

};
